<?php

use App\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CorsesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::beginTransaction();
        $courses = [
            [
                "code"            => 107,
                "course_type_id"  => 1,
                "name"            => "B.Ed.",
                "course_duration" => 2,
                "department_id"   => 1,
                "program_id"      => 2,
                "eligibility"       => "<p>Minimum 55% marks in B.A./B.Sc./B.Tech./B.E.</p>",
            ],
            [
                "code"            => 108,
                "course_type_id"  => 2,
                "name"            => "Certificate in Chinese ",
                "course_duration" => 1,
                "department_id"   => 2,
                "program_id"      => 1,
                "eligibility"       => "<p>10+2 with 45% of marks in aggregate.</p>",
            ],
            [
                "code"            => 112,
                "course_type_id"  => 3,
                "name"            => "Integrated B.Sc. B.Ed. in  Chemistry",
                "course_duration" => 4,
                "department_id"   => 3,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 114,
                "course_type_id"  => 3,
                "name"            => "Integrated B.Sc.B.Ed. in Mathemeatics",
                "course_duration" => 4,
                "department_id"   => 4,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 117,
                "course_type_id"  => 3,
                "name"            => "Integrated B.Sc. B.Ed. in Physics",
                "course_duration" => 4,
                "department_id"   => 5,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 110,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B.A. & M.A. in English",
                "course_duration" => 5,
                "department_id"   => 2,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 111,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Com. & M.Com.",
                "course_duration" => 5,
                "department_id"   => 6,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 113,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Chemistry",
                "course_duration" => 5,
                "department_id"   => 3,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 401,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Chemistry / Integrated B. Sc. B.Ed.  Chemistry",
                "course_duration" => 5,
                "department_id"   => 3,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 116,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Life Science",
                "course_duration" => 5,
                "department_id"   => 7,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 115,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Mathematics",
                "course_duration" => 5,
                "department_id"   => 4,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 118,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Physics",
                "course_duration" => 5,
                "department_id"   => 5,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 119,
                "course_type_id"  => 12,
                "name"            => "Lateral Entry to 2nd year of B.Tech",
                "course_duration" => 6,
                "department_id"   => 8,
                "program_id"      => 1,
                "eligibility"       => "<p> Diploma in Related Engineering field from an AICTE approved program. </p>\n<p> Duration of Diploma must be: </p>
            <p> (i) 03 years after 10th (Matriculation) in conventional system </p>
            <p> (ii) 04 years after 10th (Matriculation) in modular system</p>
            <p>The Candidate must have passed 10th (Matriculation) with 60% marks in aggregate and must have secured 60% marks in Mathematics, as well as must have a minimum aggregate of 70% marks at Diploma level.</p>",
            ],
            [
                "code"            => 204,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Bioelectronics",
                "course_duration" => 2,
                "department_id"   => 9,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 203,
                "course_type_id"  => 5,
                "name"            => "M. Tech. in Civil Engineering ",
                "course_duration" => 2,
                "department_id"   => 8,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 213,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Computer Science & Engineering",
                "course_duration" => 2,
                "department_id"   => 10,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 205,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Electronics Design and Technology",
                "course_duration" => 2,
                "department_id"   => 9,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 206,
                "course_type_id"  => 5,
                "name"            => "M. Tech. in Energy Technology",
                "course_duration" => 2,
                "department_id"   => 11,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 207,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Food Engineering and Technology",
                "course_duration" => 2,
                "department_id"   => 12,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 202,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Information Technology",
                "course_duration" => 2,
                "department_id"   => 10,
                "program_id"      => 2,
                "eligibility"       => "<p>B.E./B.Tech./AMIE/AMIETE in CSE/IT/ECE/allied subjects or MCA or its equivalent or M.Sc. in Computer Science/IT/Electronics/ Mathematics / Statistics with a minimum of 55% marks in aggregate. Candidates selected under GATE must possess a valid GATE score in CS.</p>",
            ],
            [
                "code"            => 208,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in Mechanical Engineering",
                "course_duration" => 2,
                "department_id"   => 13,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 218,
                "course_type_id"  => 6,
                "name"            => "M.A. in Communication for Development",
                "course_duration" => 2,
                "department_id"   => 14,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 209,
                "course_type_id"  => 6,
                "name"            => "M.A. in Cultural Studies",
                "course_duration" => 2,
                "department_id"   => 15,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 210,
                "course_type_id"  => 6,
                "name"            => "M.A. in Education",
                "course_duration" => 2,
                "department_id"   => 1,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 211,
                "course_type_id"  => 6,
                "name"            => "M.A. in English",
                "course_duration" => 2,
                "department_id"   => 2,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 214,
                "course_type_id"  => 6,
                "name"            => "M.A. in Hindi",
                "course_duration" => 2,
                "department_id"   => 16,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 212,
                "course_type_id"  => 6,
                "name"            => "M.A. in Linguistics and Language Technology",
                "course_duration" => 2,
                "department_id"   => 2,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 217,
                "course_type_id"  => 6,
                "name"            => "M.A. in Mass Communication and Journalism",
                "course_duration" => 2,
                "department_id"   => 14,
                "program_id"      => 2,
                "eligibility"       => "<p> Bachelor&rsquo;s Degree in any discipline with at least 45% marks in Major/ Honours. Candidates not having Major/ Honours must have at least 50% marks in aggregate. </p>",
            ],
            [
                "code"            => 219,
                "course_type_id"  => 6,
                "name"            => "M.A. in Social Work",
                "course_duration" => 2,
                "department_id"   => 17,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 220,
                "course_type_id"  => 6,
                "name"            => "M.A. in Sociology",
                "course_duration" => 2,
                "department_id"   => 18,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 224,
                "course_type_id"  => 7,
                "name"            => "M.Com",
                "course_duration" => 2,
                "department_id"   => 6,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 225,
                "course_type_id"  => 8,
                "name"            => "M.Sc. in Chemistry",
                "course_duration" => 2,
                "department_id"   => 3,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 227,
                "course_type_id"  => 8,
                "name"            => "M.Sc. in Environmental Science",
                "course_duration" => 2,
                "department_id"   => 19,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 228,
                "course_type_id"  => 8,
                "name"            => "M.Sc. in Mathematics",
                "course_duration" => 2,
                "department_id"   => 4,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 229,
                "course_type_id"  => 8,
                "name"            => "M.Sc. in Molecular Biology and Biotechnology",
                "course_duration" => 2,
                "department_id"   => 7,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 230,
                "course_type_id"  => 8,
                "name"            => "M.Sc. in Physics",
                "course_duration" => 2,
                "department_id"   => 5,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 201,
                "course_type_id"  => 9,
                "name"            => "Master of Computer Application (M.C.A.)",
                "course_duration" => 3,
                "department_id"   => 10,
                "program_id"      => 2,
                "eligibility"       => "<p> Bachelor's degree in any discipline with a minimum of 50% marks in major / honours subject or 55% marks in aggregate for those candidates having no major/honours or 55% marks in aggregate in BCA. Passed in Mathematics at 10+2 Examination. </p>",
            ],
            [
                "code"            => 223,
                "course_type_id"  => 9,
                "name"            => "Master of Tourism and Travel Management",
                "course_duration" => 2,
                "department_id"   => 20,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 221,
                "course_type_id"  => 10,
                "name"            => "P.G. Diploma in Child Rights and Governance",
                "course_duration" => 1,
                "department_id"   => 21,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 215,
                "course_type_id"  => 10,
                "name"            => "Post Graduate Diploma in Translation (Hindi)",
                "course_duration" => 1,
                "department_id"   => 16,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 222,
                "course_type_id"  => 10,
                "name"            => "P.G. Diploma in Women’s Studies",
                "course_duration" => 1,
                "department_id"   => 22,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
            [
                "code"            => 313,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Business Administration",
                "course_duration" => 2,
                "department_id"   => 20,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 314,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Chemical Sciences",
                "course_duration" => 2,
                "department_id"   => 3,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 301,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Civil Engineering",
                "course_duration" => 2,
                "department_id"   => 8,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 302,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Computer Science and Engineering",
                "course_duration" => 2,
                "department_id"   => 10,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 307,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Cultural Studies",
                "course_duration" => 2,
                "department_id"   => 15,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 308,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Education",
                "course_duration" => 2,
                "department_id"   => 1,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 303,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Electronics and Communication Technology",
                "course_duration" => 2,
                "department_id"   => 9,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 304,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Energy",
                "course_duration" => 2,
                "department_id"   => 11,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 309,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in English and Foreign Languages",
                "course_duration" => 2,
                "department_id"   => 2,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 315,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Environmental Science",
                "course_duration" => 2,
                "department_id"   => 19,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 305,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Food Engineering and Technology",
                "course_duration" => 2,
                "department_id"   => 12,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 310,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Hindi",
                "course_duration" => 2,
                "department_id"   => 16,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 311,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Mass Communication and Journalism",
                "course_duration" => 2,
                "department_id"   => 14,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 316,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Mathematical Sciences",
                "course_duration" => 2,
                "department_id"   => 4,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 306,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Mechanical Engineering",
                "course_duration" => 2,
                "department_id"   => 13,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 317,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Molecular Biology and Biotechnology",
                "course_duration" => 2,
                "department_id"   => 7,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 318,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Physics",
                "course_duration" => 2,
                "department_id"   => 5,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 319,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Social Work",
                "course_duration" => 2,
                "department_id"   => 17,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 312,
                "course_type_id"  => 11,
                "name"            => "Ph.D. in Sociology",
                "course_duration" => 2,
                "department_id"   => 18,
                "program_id"      => 3,
                "eligibility"       => null,
            ],
            [
                "code"            => 403,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Mathematics (5 year) / Integrated B. Sc. B.Ed.  Mathematics (4 year)",
                "course_duration" => 5,
                "department_id"   => 4,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 404,
                "course_type_id"  => 3,
                "name"            => "Integrated dual B. Sc. & M.Sc. in Physics (5 year) / Integrated B. Sc. B.Ed.  Physics (4 year)",
                "course_duration" => 5,
                "department_id"   => 5,
                "program_id"      => 1,
                "eligibility"       => "Minimum 60% aggregate marks in     Physics, Chemistry and Mathematics at 10+2 examination with minimum pass marks in individual subjects and pass mark in English.",
            ],
            [
                "code"            => 405,
                "course_type_id"  => 5,
                "name"            => "M.Tech. in IT/CSE",
                "course_duration" => 2,
                "department_id"   => 10,
                "program_id"      => 2,
                "eligibility"       => null,
            ],
        ];
        try {
            Course::truncate();
            foreach ($courses as $data) {
                Course::create($data);
            }
        } catch (Exception $e) {
            DB::rollback();
            dd($e);
        }
        DB::commit();
    }
}
