<?php

use App\Models\ExamCenter;
use Illuminate\Database\Seeder;

class ExamCentersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $array = array(
            0  => array(
                'center_code' => 101,
                'center_name' => 'Agartala',
                'address'     => 'Agartala',
                'city'        => 'Agartala',
                'state'       => null,
                'pin'         => 799001,
                'country_id'  => '1',
            ),
            1  => array(
                'center_code' => 102,
                'center_name' => 'Aizwal',
                'address'     => 'Aizwal',
                'city'        => 'Aizwal',
                'state'       => null,
                'pin'         => 796001,
                'country_id'  => '1',
            ),
            2  => array(
                'center_code' => 103,
                'center_name' => 'Barpeta Road',
                'address'     => 'Barpeta Road',
                'city'        => 'Barpeta Road',
                'state'       => null,
                'pin'         => 781315,
                'country_id'  => '1',
            ),
            3  => array(
                'center_code' => 104,
                'center_name' => 'Bengaluru',
                'address'     => 'Bengaluru',
                'city'        => 'Bengaluru',
                'state'       => null,
                'pin'         => 560001,
                'country_id'  => '1',
            ),
            4  => array(
                'center_code' => 105,
                'center_name' => 'Bhopal',
                'address'     => 'Bhopal',
                'city'        => 'Bhopal',
                'state'       => null,
                'pin'         => 462001,
                'country_id'  => '1',
            ),
            5  => array(
                'center_code' => 106,
                'center_name' => 'Bhubaneswar',
                'address'     => 'Bhubaneswar',
                'city'        => 'Bhubaneswar',
                'state'       => null,
                'pin'         => 751001,
                'country_id'  => '1',
            ),
            6  => array(
                'center_code' => 107,
                'center_name' => 'Chennai',
                'address'     => 'Chennai',
                'city'        => 'Chennai',
                'state'       => null,
                'pin'         => 600001,
                'country_id'  => '1',
            ),
            7  => array(
                'center_code' => 108,
                'center_name' => 'Delhi',
                'address'     => 'Delhi',
                'city'        => 'Delhi',
                'state'       => null,
                'pin'         => 110001,
                'country_id'  => '1',
            ),
            8  => array(
                'center_code' => 109,
                'center_name' => 'Dibrugarh',
                'address'     => 'Dibrugarh',
                'city'        => 'Dibrugarh',
                'state'       => null,
                'pin'         => 786001,
                'country_id'  => '1',
            ),
            9  => array(
                'center_code' => 110,
                'center_name' => 'Diphu',
                'address'     => 'Diphu',
                'city'        => 'Diphu',
                'state'       => null,
                'pin'         => 782460,
                'country_id'  => '1',
            ),
            10 => array(
                'center_code' => 111,
                'center_name' => 'Gangtok',
                'address'     => 'Gangtok',
                'city'        => 'Gangtok',
                'state'       => null,
                'pin'         => 737101,
                'country_id'  => '1',
            ),
            11 => array(
                'center_code' => 112,
                'center_name' => 'Goalpara',
                'address'     => 'Goalpara',
                'city'        => 'Goalpara',
                'state'       => null,
                'pin'         => 783101,
                'country_id'  => '1',
            ),
            12 => array(
                'center_code' => 113,
                'center_name' => 'Guwahati (GU)',
                'address'     => 'Guwahati',
                'city'        => 'Guwahati',
                'state'       => null,
                'pin'         => 781014,
                'country_id'  => '1',
            ),
            13 => array(
                'center_code' => 114,
                'center_name' => 'Guwahati (NERIM)',
                'address'     => 'Guwahati',
                'city'        => 'Guwahati',
                'state'       => null,
                'pin'         => 781022,
                'country_id'  => '1',
            ),
            14 => array(
                'center_code' => 115,
                'center_name' => 'Hyderabad',
                'address'     => 'Hyderabad',
                'city'        => 'Hyderabad',
                'state'       => null,
                'pin'         => 500001,
                'country_id'  => '1',
            ),
            15 => array(
                'center_code' => 116,
                'center_name' => 'Imphal',
                'address'     => 'Imphal',
                'city'        => 'Imphal',
                'state'       => null,
                'pin'         => 795001,
                'country_id'  => '1',
            ),
            16 => array(
                'center_code' => 117,
                'center_name' => 'Itanagar',
                'address'     => 'Itanagar',
                'city'        => 'Itanagar',
                'state'       => null,
                'pin'         => 791111,
                'country_id'  => '1',
            ),
            17 => array(
                'center_code' => 118,
                'center_name' => 'Jorhat',
                'address'     => 'Jorhat',
                'city'        => 'Jorhat',
                'state'       => null,
                'pin'         => 785001,
                'country_id'  => '1',
            ),
            18 => array(
                'center_code' => 119,
                'center_name' => 'Kanpur',
                'address'     => 'Kanpur',
                'city'        => 'Kanpur',
                'state'       => null,
                'pin'         => 208001,
                'country_id'  => '1',
            ),
            19 => array(
                'center_code' => 120,
                'center_name' => 'Kohima',
                'address'     => 'Kohima',
                'city'        => 'Kohima',
                'state'       => null,
                'pin'         => 797001,
                'country_id'  => '1',
            ),
            20 => array(
                'center_code' => 121,
                'center_name' => 'Kokrajhar',
                'address'     => 'Kokrajhar',
                'city'        => 'Kokrajhar',
                'state'       => null,
                'pin'         => 783370,
                'country_id'  => '1',
            ),
            21 => array(
                'center_code' => 122,
                'center_name' => 'Kolkata',
                'address'     => 'Kolkata',
                'city'        => 'Kolkata',
                'state'       => null,
                'pin'         => 700001,
                'country_id'  => '1',
            ),
            22 => array(
                'center_code' => 123,
                'center_name' => 'North Lakhimpur',
                'address'     => 'North Lakhimpur',
                'city'        => 'North Lakhimpur',
                'state'       => null,
                'pin'         => 787001,
                'country_id'  => '1',
            ),
            23 => array(
                'center_code' => 124,
                'center_name' => 'Patna',
                'address'     => 'Patna',
                'city'        => 'Patna',
                'state'       => null,
                'pin'         => 800001,
                'country_id'  => '1',
            ),
            24 => array(
                'center_code' => 125,
                'center_name' => 'Pune',
                'address'     => 'Pune',
                'city'        => 'Pune',
                'state'       => null,
                'pin'         => 111045,
                'country_id'  => '1',
            ),
            25 => array(
                'center_code' => 126,
                'center_name' => 'Ranchi',
                'address'     => 'Ranchi',
                'city'        => 'Ranchi',
                'state'       => null,
                'pin'         => 834001,
                'country_id'  => '1',
            ),
            26 => array(
                'center_code' => 127,
                'center_name' => 'Shillong',
                'address'     => 'Shillong',
                'city'        => 'Shillong',
                'state'       => null,
                'pin'         => 793001,
                'country_id'  => '1',
            ),
            27 => array(
                'center_code' => 128,
                'center_name' => 'Silchar',
                'address'     => 'Silchar',
                'city'        => 'Silchar',
                'state'       => null,
                'pin'         => 788001,
                'country_id'  => '1',
            ),
            28 => array(
                'center_code' => 129,
                'center_name' => 'Siliguri',
                'address'     => 'Siliguri',
                'city'        => 'Siliguri',
                'state'       => null,
                'pin'         => 734001,
                'country_id'  => '1',
            ),
            29 => array(
                'center_code' => 130,
                'center_name' => 'Tezpur',
                'address'     => 'Tezpur',
                'city'        => 'Tezpur',
                'state'       => null,
                'pin'         => 784001,
                'country_id'  => '1',
            ),
            30 => array(
                'center_code' => 201,
                'center_name' => 'Dhaka',
                'address'     => 'Dhaka',
                'city'        => 'Dhaka',
                'state'       => null,
                'pin'         => 1205,
                'country_id'  => '2',
            ),
            31 => array(
                'center_code' => 202,
                'center_name' => 'Thimphu',
                'address'     => 'Thimphu',
                'city'        => 'Thimphu',
                'state'       => null,
                'pin'         => 11001,
                'country_id'  => '3',
            ),
            32 => array(
                'center_code' => 203,
                'center_name' => 'Kathmandu',
                'address'     => 'Kathmandu',
                'city'        => 'Kathmandu',
                'state'       => null,
                'pin'         => 44600,
                'country_id'  => '4',
            ),
        );
        ExamCenter::truncate();
        foreach ($array as $data) {
            ExamCenter::create($data);
        }
    }
}
